package p042bo.app;

import kotlin.jvm.internal.C12775o;

/* renamed from: bo.app.r5 */
public final class C3638r5 extends Exception {
    /* JADX INFO: super call moved to the top of the method (can break code semantics) */
    public C3638r5(String str, Throwable th) {
        super(str, th);
        C12775o.m28639i(str, "message");
        C12775o.m28639i(th, "innerException");
    }
}
